language: ruby
rvm:
  - 2.1.2
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - "export JASMINE_SPEC_FORMAT=documentation"
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate"
  - "bundle exec rake spec"
  - "bundle exec rake spec:javascript"
env:
  - PG_USERNAME='postgres'
